### ISSUE TITLE
Can't export SBML file

### ISSUE THREAD

**Issue by mauriceccy** [mauriceccy/scobra#13]
Problem with exporting SBML file, e.g. https://static-content.springer.com/esm/art%3A10.1038%2Fs41477-018-0112-2/MediaObjects/41477_2018_112_MOESM3_ESM.xml

Potentially because of wrong default arguments used.

**Comment by ajsanjoaquin** [comment]
Hi Maurice,
HEXOKINASE_RXN_MANNOSE_c1 & HEXOKINASE_RXN_MANNOSE_c2 are causing the export error. When you read the file, cobra flags a warning that they are a malformed gene.

<img width="619" alt="p" src="https://user-images.githubusercontent.com/42886152/66713238-bb261780-edda-11e9-8335-5fd44762192b.PNG">

They produce a type error that prevents the file to be exported as sbml. The correct WriteModel arguments can be found here:
<img width="619" alt="Capture" src="https://user-images.githubusercontent.com/42886152/66713250-ea3c8900-edda-11e9-8fb9-b72ec8ab4dff.PNG">

I deleted the two reactions, and I was able to export them successfully. I also read and exported an sbml file taken online. I suggest you reformat these two reactions because their format may be corrupted.
